./sudoku problems/20070708.txt | tee solutions/20070708.sol
./sudoku problems/20070715.txt | tee solutions/20070715.sol
./sudoku problems/20070727.txt | tee solutions/20070727.sol
./sudoku problems/20091218.txt | tee solutions/20091218.sol
./sudoku problems/chron2.txt   | tee solutions/chron2.sol 
./sudoku problems/crook-01.txt | tee solutions/crook-01.sol
./sudoku problems/crook-02.txt | tee solutions/crook-02.sol
./sudoku problems/crook-03.txt | tee solutions/crook-03.sol
./sudoku problems/crook-04.txt | tee solutions/crook-04.sol
./sudoku problems/dany01.txt   | tee solutions/dany01.sol
./sudoku problems/diabol1.txt  | tee solutions/diabol1.sol 
./sudoku problems/evil.txt     | tee solutions/evil.sol    
./sudoku problems/hard-01.txt  | tee solutions/hard-01.sol 
./sudoku problems/hard-02.txt  | tee solutions/hard-02.sol 
./sudoku problems/hard-03.txt  | tee solutions/hard-03.sol 
./sudoku problems/houston1.txt | tee solutions/houston1.sol
./sudoku problems/houston2.txt | tee solutions/houston2.sol
./sudoku problems/houston3.txt | tee solutions/houston3.sol
./sudoku problems/houston4.txt | tee solutions/houston4.sol
./sudoku problems/mathin41.txt | tee solutions/mathin41.sol
./sudoku problems/mathin42.txt | tee solutions/mathin42.sol
./sudoku problems/mathin9.txt  | tee solutions/mathin9.sol 
./sudoku problems/monster.txt  | tee solutions/monster.sol 
./sudoku problems/murty-01.txt | tee solutions/murty-01.sol
./sudoku problems/murty-02.txt | tee solutions/murty-02.sol
./sudoku problems/murty-03.txt | tee solutions/murty-03.sol
./sudoku problems/n-eq-3.txt   | tee solutions/n-eq-3.sol
./sudoku problems/n-eq-4.txt   | tee solutions/n-eq-4.sol
./sudoku problems/s1.txt       | tee solutions/s1.sol      
./sudoku problems/s2.txt       | tee solutions/s2.sol      
./sudoku problems/s3.txt       | tee solutions/s3.sol      
./sudoku problems/s4.txt       | tee solutions/s4.sol      
./sudoku problems/s5.txt       | tee solutions/s5.sol     
./sudoku problems/s6.txt       | tee solutions/s6.sol      
./sudoku problems/templat4.txt | tee solutions/templat4.sol
./sudoku problems/template.txt | tee solutions/template.sol
