sudoku problems\20070708.txt >solutions\20070708.sol
sudoku problems\20070715.txt >solutions\20070715.sol
sudoku problems\20070727.txt >solutions\20070727.sol
sudoku problems\20091218.txt >solutions\20091218.sol
sudoku problems\chron2.txt   >solutions\chron2.sol 
sudoku problems\crook-01.txt >solutions\crook-01.sol
sudoku problems\crook-02.txt >solutions\crook-02.sol
sudoku problems\crook-03.txt >solutions\crook-03.sol
sudoku problems\crook-04.txt >solutions\crook-04.sol
sudoku problems\dany01.txt   >solutions\dany01.sol
sudoku problems\diabol1.txt  >solutions\diabol1.sol 
sudoku problems\evil.txt     >solutions\evil.sol    
sudoku problems\hard-01.txt  >solutions\hard-01.sol 
sudoku problems\hard-02.txt  >solutions\hard-02.sol 
sudoku problems\hard-03.txt  >solutions\hard-03.sol 
sudoku problems\houston1.txt >solutions\houston1.sol
sudoku problems\houston2.txt >solutions\houston2.sol
sudoku problems\houston3.txt >solutions\houston3.sol
sudoku problems\houston4.txt >solutions\houston4.sol
sudoku problems\mathin41.txt >solutions\mathin41.sol
sudoku problems\mathin42.txt >solutions\mathin42.sol
sudoku problems\mathin9.txt  >solutions\mathin9.sol 
sudoku problems\monster.txt  >solutions\monster.sol 
sudoku problems\murty-01.txt >solutions\murty-01.sol
sudoku problems\murty-02.txt >solutions\murty-02.sol
sudoku problems\murty-03.txt >solutions\murty-03.sol
sudoku problems\n-eq-3.txt   >solutions\n-eq-3.sol
sudoku problems\n-eq-4.txt   >solutions\n-eq-4.sol
sudoku problems\s1.txt       >solutions\s1.sol      
sudoku problems\s2.txt       >solutions\s2.sol      
sudoku problems\s3.txt       >solutions\s3.sol      
sudoku problems\s4.txt       >solutions\s4.sol      
sudoku problems\s5.txt       >solutions\s5.sol     
sudoku problems\s6.txt       >solutions\s6.sol      
sudoku problems\templat4.txt >solutions\templat4.sol
sudoku problems\template.txt >solutions\template.sol
